services:
  web:
    container_name: patient
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    networks:
      - dash_net
  dash:
    container_name: dash_app
    build: ./dash_app
    command: python dash_app.py
    restart: unless-stopped
    ports:
      - 8050:8050
    env_file:
      - ./.env.dev
    depends_on:
      - web
    networks:
      - dash_net


volumes:
  postgres_data:
  pgadmin-data:

networks:
  dash_net:
    driver: bridge
