# Generated by Django 5.2.3 on 2025-06-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('sex', models.SmallIntegerField(choices=[(1, 'Мужской'), (2, 'Женский')], verbose_name='Пол')),
                ('cure_order', models.SmallIntegerField(choices=[(1, 'Первичный пациент'), (2, 'Вторичный пациент')], verbose_name='Первичный/вторичный')),
                ('last_contact_date', models.DateField(verbose_name='Дата последнего контакта/смерти')),
                ('statendyr', models.SmallIntegerField(choices=[(1, 'Жив'), (2, 'Умер от осложнения лечения'), (3, 'Умер от основного заболевания'), (4, 'Умер от других заболеваний'), (5, 'Выехал'), (7, 'Диагноз не подтвердился'), (8, 'Снят с учета в связи с истечением срока наблюдения')], verbose_name='Состояние на данный момент')),
                ('prrecid', models.SmallIntegerField(choices=[(1, 'Рецидив'), (2, 'Регионарные метастазы'), (3, 'Отдаленные метастазы'), (4, 'Биохимический рецидив'), (5, 'Прогрессирование процесса'), (6, 'Местнораспространенный процесс'), (7, 'Трансформация')], verbose_name='Возникший процесс')),
                ('prrecid_date', models.DateField(verbose_name='Дата возникновения процесса')),
                ('datediag', models.DateField(verbose_name='Дата возникновения процесса')),
                ('mkb10', models.CharField(max_length=7, verbose_name='МКБ-10')),
                ('txtdiag', models.CharField(max_length=400, verbose_name='Диагноз текстом')),
                ('stage', models.SmallIntegerField(verbose_name='Стадия')),
                ('t', models.SmallIntegerField(verbose_name='T')),
                ('n', models.SmallIntegerField(verbose_name='N')),
                ('m', models.SmallIntegerField(verbose_name='M')),
                ('g', models.SmallIntegerField(verbose_name='G')),
                ('p16', models.SmallIntegerField(verbose_name='p16')),
                ('focus_size', models.FloatField(verbose_name='Размер первичного очага, см')),
                ('node_size', models.FloatField(verbose_name='Размер л/у, см')),
                ('note_txt', models.CharField(max_length=200, verbose_name='Текстовая пометка')),
                ('oper_date', models.DateField(verbose_name='Дата операции')),
                ('oper_txt', models.CharField(max_length=400, verbose_name='Операция текстом')),
                ('oper_complications', models.CharField(max_length=200, verbose_name='Послеоперационные осложнения, текстом')),
                ('dendritic', models.BooleanField(verbose_name='Введение дендритных клеток')),
                ('kindlech_txt', models.CharField(max_length=200, verbose_name='Вид специального лечения')),
                ('fk_after', models.CharField(max_length=200, verbose_name='ФК после')),
                ('fk_last', models.CharField(max_length=200, verbose_name='ФК последнее')),
                ('neut', models.FloatField(verbose_name='Нейтрофилы')),
                ('limph', models.FloatField(verbose_name='Лимфоциты')),
                ('plt', models.FloatField(verbose_name='Тромбоциты')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
                'ordering': ['fio'],
            },
        ),
    ]
