# Generated by Django 5.2.3 on 2025-06-15 01:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='actual_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Вся информация о пациенте актуальна на: (дата)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего редактирования'),
        ),
    ]
