# Generated by Django 5.2.3 on 2025-06-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_actual_date_patient_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='actual_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Вся информация о пациенте актуальна на: (дата)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cure_order',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Первичный пациент'), (2, 'Вторичный пациент')], null=True, verbose_name='Первичный/вторичный'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='datediag',
            field=models.DateField(blank=True, null=True, verbose_name='Дата возникновения процесса'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dendritic',
            field=models.BooleanField(blank=True, null=True, verbose_name='Введение дендритных клеток'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fk_after',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ФК после'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fk_last',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ФК последнее'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='focus_size',
            field=models.FloatField(blank=True, null=True, verbose_name='Размер первичного очага, см'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='g',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='G'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='kindlech_txt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вид специального лечения'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_contact_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего контакта/смерти'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='limph',
            field=models.FloatField(blank=True, null=True, verbose_name='Лимфоциты'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='m',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='M'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mkb10',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='МКБ-10'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='n',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='N'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='neut',
            field=models.FloatField(blank=True, null=True, verbose_name='Нейтрофилы'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='node_size',
            field=models.FloatField(blank=True, null=True, verbose_name='Размер л/у, см'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='note_txt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Текстовая пометка'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='oper_complications',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Послеоперационные осложнения, текстом'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='oper_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата операции'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='oper_txt',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Операция текстом'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='p16',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='p16'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='plt',
            field=models.FloatField(blank=True, null=True, verbose_name='Тромбоциты'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prrecid',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Рецидив'), (2, 'Регионарные метастазы'), (3, 'Отдаленные метастазы'), (4, 'Биохимический рецидив'), (5, 'Прогрессирование процесса'), (6, 'Местнораспространенный процесс'), (7, 'Трансформация')], null=True, verbose_name='Возникший процесс'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prrecid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата возникновения процесса'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Мужской'), (2, 'Женский')], null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='stage',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Стадия'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='statendyr',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Жив'), (2, 'Умер от осложнения лечения'), (3, 'Умер от основного заболевания'), (4, 'Умер от других заболеваний'), (5, 'Выехал'), (7, 'Диагноз не подтвердился'), (8, 'Снят с учета в связи с истечением срока наблюдения')], null=True, verbose_name='Состояние на данный момент'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='t',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='T'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='txtdiag',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Диагноз текстом'),
        ),
    ]
