# Generated by Django 5.2.3 on 2025-06-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_actual_date_alter_patient_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mkb10',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='МКБ-10'),
        ),
    ]
