# Generated by Django 5.2.3 on 2025-06-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_mkb10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='txtdiag',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Диагноз текстом'),
        ),
    ]
